version: '3.0'

services:
  fastapi-todos-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi_todos
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  fastapi-todos-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      fastapi-todos-mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 3000:3000
